travis: Use GCC 5.4 instead of 5.5
GCC 5.4 is the default version in Xenial. We do not explicitly request
gcc-5, which maps to GCC 5.5.

This is to avoid the following errors produced by NVCC:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9220): error: argument of type "const void *" is incompatible with parameter of type "const float *"